parameters:
#    acme_zayavki.example.class: Acme\ZayavkiBundle\Example
    transloc.class: Acme\ZayavkiBundle\Model\Transloc
imports:
- { resource: databases.yml }
services:
    transloc:
        class: "%transloc.class%"
        calls:
          - [ setContainer,[ @service_container ] ]
#    acme_zayavki.example:
#        class: %acme_zayavki.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


