parameters:
#    acme_zayavki.example.class: Acme\ZayavkiBundle\Example
#    user_provider.class: Acme\ZayavkiBundle\Entity\UserProvider

services:
#    user_provider:
#        class: "%user_provider.class%"
#    acme_zayavki.example:
#        class: %acme_zayavki.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


