security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check		
            logout:
                path:   /logout
                target: /index				
        #    http_basic:
        #        realm: "Secured Demo Area"
    access_control:
        - { path: ^/index, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }		
        # Include the following line to also secure the /admin path itself
        # - { path: ^/admin$, roles: ROLE_ADMIN }

    providers:
#        webservice:
#            id: user_provider	
         main:  
            entity:
                class: Acme\ZayavkiBundle\Entity\User
    encoders:
      #  Symfony\Component\Security\Core\User\User: plaintext
        Acme\ZayavkiBundle\Entity\User: plaintext
      #  Acme\ZayavkiBundle\Entity\User: 
      #       algorithm: bcrypt
      #       cost: 12		